name: ghex

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test-ghex:
    if: false
    uses: ./.github/workflows/common.yml
    strategy:
      matrix:
        #package-version: ['0.4.1', 'master']
        package-version: ['master']
        compiler: ['gcc@13.3.0']
        #backend: ['mpi', 'ucx', 'libfabric']
        backend: ['mpi']
        python-bindings: [true]
        device: ['cpu']
    with:
      package-name: ghex
      package-version: ${{ matrix.package-version }}
      package-variants: >-
        %${{ matrix.compiler }}
        backend=${{ matrix.backend }}
        ${{ matrix.python-bindings && '+python' || '' }}
        ${{ matrix.device == 'cuda' && '+cuda' || '' }}
        ${{ matrix.device == 'rocm' && '+rocm' || '' }}
      test-package: ${{ matrix.device == 'cpu' }}
