name: ghex

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-ghex:
    uses: ./.github/workflows/common.yml
    strategy:
      matrix:
        package-version: ['0.4.1', 'master']
        backends: ['mpi', 'ucx', 'libfabric']
        python-bindings: [true]
        fortran-bindings: [true]
    with:
      package-name: ghex
      package-version: ${{ matrix.package-version }}
      package-variants: >-
        backends=${{ matrix.backends }}
        ${{ matrix.python-bindings == 'true' && '+python-bindings' || '' }}
        ${{ matrix.fortran-bindings == 'true' && '+fortran-bindings' || '' }}
