name: ghex

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test-ghex:
    uses: ./.github/workflows/common.yml
    strategy:
      matrix:
        #package-version: ['0.4.1', 'master']
        package-version: ['master']
        #backend: ['mpi', 'ucx', 'libfabric']
        backend: ['mpi']
        python-bindings: [true]
        fortran-bindings: [true]
    with:
      package-name: ghex
      package-version: ${{ matrix.package-version }}
      package-variants: >-
        backend=${{ matrix.backend }}
        ${{ matrix.python-bindings == 'true' && '+python-bindings' || '' }}
        ${{ matrix.fortran-bindings == 'true' && '+fortran-bindings' || '' }}
