name: test-hwmalloc

on:
  push:
  pull_request:
    # branches:
    #   - main

jobs:
  spack-install:
    runs-on: ubuntu-latest
    container: boeschf/ghex-org
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build and test
        run: |
          . /opt/spack/share/spack/setup-env-clean.sh
          spack repo add .
          spack spec -I hwmalloc
          spack install --test=root --verbose --show-log-on-error hwmalloc
