name: hwmalloc

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-hwmalloc:
    uses: ./.github/workflows/common.yml
    strategy:
      matrix:
        package-version: ['0.3.0', 'master']
        package-variants: ['']
    with:
      package-name: hwmalloc
      package-version: ${{ matrix.package-version }}
      package-variants: ${{ matrix.package-variants }}
