name: test-hwmalloc

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  spack-install:
    runs-on: ubuntu-${{ matrix.ubuntu-version }}

    permissions:
      packages: write

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ubuntu-version: ['22.04']
        micro-arch: ['x86_64_v3']
        version: ['0.2.0', '0.3.0']
        spack-config:
        - {
            version:    'v0.21.2',
            add-mirror: 'spack mirror add',
            install:    'spack install --no-check-signature',
            push-buildcache:    'spack buildcache push',
          }
        - {
            version:    'develop',
            add-mirror: 'spack mirror add --unsigned',
            install:    'spack install',
            push-buildcache:    'spack buildcache push',
          }

      fail-fast: false

    env:
      SPACK_DISABLE_LOCAL_CONFIG:     "true"
      SPACK_USER_CACHE_PATH:          "/tmp/spack"

    steps:

      - name: install additional ubuntu packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gfortran

      - name: checkout
        uses: actions/checkout@v4

      - name: clone spack
        run: git clone -c feature.manyFiles=true --depth 1 --branch ${{ matrix.spack-config.version }} https://github.com/spack/spack.git spack

      - name: initialize spack and add online buildcache
        run: |
          cat <<EOF > spack/etc/spack/config.yaml
          config:
            install_tree:
              padded_length: 128
            build_jobs: 4
          EOF

          cat <<EOF > spack/etc/spack/packages.yaml
          packages:
            all:
              require:
              - 'target=${{ matrix.micro-arch }}'
              - '%gcc'
          EOF

          source spack/share/spack/setup-env.sh
          spack compiler find
          ${{ matrix.spack-config.add-mirror }} local-buildcache oci://ghcr.io/boeschf/spack-buildcache-ubuntu-${{ matrix.ubuntu-version }}-spack-${{ matrix.spack-config.version }}
          spack repo add .
          spack reindex

      - name: build-and-test
        run: |
          source spack/share/spack/setup-env.sh
          # print dependencies
          spack spec -I hwmalloc@${{ matrix.version }}
          # install package
          ${{ matrix.spack-config.install }} --test=root --verbose --show-log-on-error hwmalloc@${{ matrix.version }}

      - name: Push packages and update index
        continue-on-error: true
        run: |
          source spack/share/spack/setup-env.sh
          spack mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
          ${{ matrix.spack-config.push-buildcache }} --base-image ubuntu:${{ matrix.ubuntu-version }} --unsigned --update-index --only dependencies local-buildcache hwmalloc@${{ matrix.version }}
