name: oomph

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test-oomph:
    uses: ./.github/workflows/common.yml
    strategy:
      matrix:
        package-version: ['0.4.0', 'main']
        compiler: ['gcc@13.3.0']
        backend: ['mpi', 'ucx', 'libfabric']
        fortran-bindings: [false]
        #device: ['cpu', 'cuda']
        device: ['cpu']
    with:
      package-name: oomph
      package-version: ${{ matrix.package-version }}
      package-variants: >-
        %${{ matrix.compiler }}
        backend=${{ matrix.backend }}
        ${{ matrix.fortran-bindings && '+fortran-bindings' || '' }}
        ${{ matrix.device == 'cuda' && '+cuda cuda_arch=90' || '' }}
        ${{ matrix.device == 'rocm' && '+rocm amdgpu_target=gfx942' || '' }}
      test-package: ${{ matrix.device == 'cpu' }}
