name: test-oomph

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  spack-install:
    runs-on: ubuntu-latest
    container: boeschf/ghex-org
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build and test
        shell: bash
        run: |
          . /opt/spack/share/spack/setup-env-clean.sh
          spack repo add .
          spack spec -I oomph
          spack install --test=root --verbose --show-log-on-error oomph
          cat /tmp/root/spack-stage/spack-stage-oomph-0.2.0-xt3kmiaaqzmzun6bmunula2iaearyp2j/spack-build-xt3kmia/Testing/Temporary/LastTest.log

