name: oomph

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-oomph:
    uses: ./.github/workflows/common.yml
    strategy:
      matrix:
        package-version: ['0.3.0', 'main']
        backend: ['mpi', 'ucx', 'libfabric']
        fortran-bindings: [true]
    with:
      package-name: oomph
      package-version: ${{ matrix.package-version }}
      package-variants: >-
        backend=${{ matrix.backend }}
        ${{ matrix.fortran-bindings == 'true' && '+fortran-bindings' || '' }}
